/*
 * tyb-abi.js — GENERATED by Code/tyb-contracts/tools/gen-front-abi.mjs. DO NOT EDIT BY HAND.
 * Full ABI (functions + errors + events) of the TYB Robinhood contracts, so ethers v6 can decode EVERY custom
 * error into err.revert.name (the seam maps names → copy). Regenerate after any `forge build`; the parity test
 * (tyb-seam-parity.test.mjs) fails on drift. Counts: {"TYB721":{"fns":71,"errors":54,"events":23},"TYBGacha":{"fns":65,"errors":30,"events":27},"TYBPowerUp1155":{"fns":26,"errors":23,"events":10},"TYBEvolution":{"fns":13,"errors":12,"events":3},"TYBRenderer":{"fns":4,"errors":5,"events":1}}
 */
(function () {
  'use strict';
  var TYB_ABI = Object.freeze({
 "TYB721": [
  {
   "type": "error",
   "name": "AlreadyRevealed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "AlreadySet",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ApprovalCallerNotOwnerNorApproved",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ApprovalQueryForNonexistentToken",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadProof",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadQuantity",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadRenderer",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadURI",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BalanceQueryForZeroAddress",
   "inputs": []
  },
  {
   "type": "error",
   "name": "CreatorTokenBase__InvalidTransferValidatorContract",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ERC2981InvalidDefaultRoyalty",
   "inputs": [
    {
     "name": "numerator",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "denominator",
     "type": "uint256",
     "internalType": "uint256"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidDefaultRoyaltyReceiver",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidTokenRoyalty",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "numerator",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "denominator",
     "type": "uint256",
     "internalType": "uint256"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidTokenRoyaltyReceiver",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "GtdAllowanceExceeded",
   "inputs": []
  },
  {
   "type": "error",
   "name": "InsolventWithdraw",
   "inputs": []
  },
  {
   "type": "error",
   "name": "InvalidQueryRange",
   "inputs": []
  },
  {
   "type": "error",
   "name": "MintERC2309QuantityExceedsLimit",
   "inputs": []
  },
  {
   "type": "error",
   "name": "MintPausedErr",
   "inputs": []
  },
  {
   "type": "error",
   "name": "MintToZeroAddress",
   "inputs": []
  },
  {
   "type": "error",
   "name": "MintZeroQuantity",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NonexistentToken",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotCompatibleWithSpotMints",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotEvolution",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotMinter",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotOwner",
   "inputs": []
  },
  {
   "type": "error",
   "name": "OwnableInvalidOwner",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "OwnableUnauthorizedAccount",
   "inputs": [
    {
     "name": "account",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "OwnerQueryForNonexistentToken",
   "inputs": []
  },
  {
   "type": "error",
   "name": "OwnershipNotInitializedForExtraData",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ReentrancyGuardReentrantCall",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RefundNotClosed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RefundNotOpened",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RefundTransferFailed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RefundWindowClosed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RenounceBlocked",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RootNotSet",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RoyaltyTooHigh",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SequentialMintExceedsLimit",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SequentialUpToTooSmall",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ShouldNotMintToBurnAddress",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SoldOut",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SpotMintTokenIdTooSmall",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TokenAlreadyExists",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TransferCallerNotOwnerNorApproved",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TransferFromIncorrectOwner",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TransferToNonERC721ReceiverImplementer",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TransferToZeroAddress",
   "inputs": []
  },
  {
   "type": "error",
   "name": "URIQueryForNonexistentToken",
   "inputs": []
  },
  {
   "type": "error",
   "name": "WalletCapExceeded",
   "inputs": []
  },
  {
   "type": "error",
   "name": "WithdrawFailed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "WrongPhase",
   "inputs": []
  },
  {
   "type": "error",
   "name": "WrongValue",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ZeroAddress",
   "inputs": []
  },
  {
   "type": "event",
   "name": "Approval",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "approved",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "ApprovalForAll",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "operator",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "approved",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "AutomaticApprovalOfTransferValidatorSet",
   "inputs": [
    {
     "name": "autoApproved",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "BatchMetadataUpdate",
   "inputs": [
    {
     "name": "_fromTokenId",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "_toTokenId",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "ConsecutiveTransfer",
   "inputs": [
    {
     "name": "fromTokenId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "toTokenId",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "from",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "DefaultRoyaltySet",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "feeBps",
     "type": "uint96",
     "indexed": false,
     "internalType": "uint96"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "EvolutionSet",
   "inputs": [
    {
     "name": "evolution",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "FcfsRootSet",
   "inputs": [
    {
     "name": "root",
     "type": "bytes32",
     "indexed": false,
     "internalType": "bytes32"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "GtdRootSet",
   "inputs": [
    {
     "name": "root",
     "type": "bytes32",
     "indexed": false,
     "internalType": "bytes32"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "MetadataUpdate",
   "inputs": [
    {
     "name": "_tokenId",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "MintPausedSet",
   "inputs": [
    {
     "name": "paused",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OwnershipTransferred",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OwnershipTransferStarted",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "PhaseAdvanced",
   "inputs": [
    {
     "name": "phase",
     "type": "uint8",
     "indexed": false,
     "internalType": "enum TYB721.Phase"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RaffleSet",
   "inputs": [
    {
     "name": "raffle",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RefundClosed",
   "inputs": [],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Refunded",
   "inputs": [
    {
     "name": "minter",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "count",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RefundOpened",
   "inputs": [],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RendererSet",
   "inputs": [
    {
     "name": "renderer",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Revealed",
   "inputs": [],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Transfer",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "TransferValidatorUpdated",
   "inputs": [
    {
     "name": "oldValidator",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    },
    {
     "name": "newValidator",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Withdrawn",
   "inputs": [
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "function",
   "name": "acceptOwnership",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "advancePhase",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "approve",
   "inputs": [
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "autoApproveTransfersFromValidator",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "balanceOf",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "BPS_DENOM",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "closeRefund",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "DEFAULT_TRANSFER_VALIDATOR",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "evolution",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "explicitOwnershipOf",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "ownership",
     "type": "tuple",
     "internalType": "struct IERC721A.TokenOwnership",
     "components": [
      {
       "name": "addr",
       "type": "address",
       "internalType": "address"
      },
      {
       "name": "startTimestamp",
       "type": "uint64",
       "internalType": "uint64"
      },
      {
       "name": "burned",
       "type": "bool",
       "internalType": "bool"
      },
      {
       "name": "extraData",
       "type": "uint24",
       "internalType": "uint24"
      }
     ]
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "explicitOwnershipsOf",
   "inputs": [
    {
     "name": "tokenIds",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "tuple[]",
     "internalType": "struct IERC721A.TokenOwnership[]",
     "components": [
      {
       "name": "addr",
       "type": "address",
       "internalType": "address"
      },
      {
       "name": "startTimestamp",
       "type": "uint64",
       "internalType": "uint64"
      },
      {
       "name": "burned",
       "type": "bool",
       "internalType": "bool"
      },
      {
       "name": "extraData",
       "type": "uint24",
       "internalType": "uint24"
      }
     ]
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "fcfsRoot",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "getApproved",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "getTransferValidationFunction",
   "inputs": [],
   "outputs": [
    {
     "name": "functionSignature",
     "type": "bytes4",
     "internalType": "bytes4"
    },
    {
     "name": "isViewFunction",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "pure"
  },
  {
   "type": "function",
   "name": "getTransferValidator",
   "inputs": [],
   "outputs": [
    {
     "name": "validator",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "gtdMinted",
   "inputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "gtdRoot",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "isApprovedForAll",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "operator",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "MAX_PER_WALLET",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "MAX_SUPPLY",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "mintFcfs",
   "inputs": [
    {
     "name": "qty",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "proof",
     "type": "bytes32[]",
     "internalType": "bytes32[]"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "mintGtd",
   "inputs": [
    {
     "name": "qty",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "allowedQty",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "proof",
     "type": "bytes32[]",
     "internalType": "bytes32[]"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "mintPaused",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "mintPublic",
   "inputs": [
    {
     "name": "qty",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "name",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "string",
     "internalType": "string"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "numberMinted",
   "inputs": [
    {
     "name": "a",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "openRefund",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "originalMinter",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "owner",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "ownerOf",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pendingOwner",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "phase",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint8",
     "internalType": "enum TYB721.Phase"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pingMetadataUpdate",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "PRICE",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "raffle",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "REFUND_BPS",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "REFUND_PER_TOKEN",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "refund",
   "inputs": [
    {
     "name": "ids",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "refundClosed",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "refundClosedLatch",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "refundLiability",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "refundOpen",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "renderer",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "renounceOwnership",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "reveal",
   "inputs": [
    {
     "name": "baseURI_",
     "type": "string",
     "internalType": "string"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "revealed",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "royaltyInfo",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "salePrice",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "safeTransferFrom",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "_data",
     "type": "bytes",
     "internalType": "bytes"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "safeTransferFrom",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "setApprovalForAll",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "approved",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setAutomaticApprovalOfTransfersFromValidator",
   "inputs": [
    {
     "name": "autoApprove",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setDefaultRoyalty",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "feeBps",
     "type": "uint96",
     "internalType": "uint96"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setEvolution",
   "inputs": [
    {
     "name": "e",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setFcfsRoot",
   "inputs": [
    {
     "name": "root",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setGtdRoot",
   "inputs": [
    {
     "name": "root",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setMintPaused",
   "inputs": [
    {
     "name": "p",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setRaffle",
   "inputs": [
    {
     "name": "r",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setRenderer",
   "inputs": [
    {
     "name": "r",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setTransferValidator",
   "inputs": [
    {
     "name": "transferValidator_",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setUnrevealedURI",
   "inputs": [
    {
     "name": "uri",
     "type": "string",
     "internalType": "string"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "supportsInterface",
   "inputs": [
    {
     "name": "interfaceId",
     "type": "bytes4",
     "internalType": "bytes4"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "symbol",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "string",
     "internalType": "string"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "tokensOfOwner",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "tokensOfOwnerIn",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "start",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "stop",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "tokenURI",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "string",
     "internalType": "string"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "totalMintedEver",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "totalSupply",
   "inputs": [],
   "outputs": [
    {
     "name": "result",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "transferFrom",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "transferOwnership",
   "inputs": [
    {
     "name": "newOwner",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "VERSION",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "withdraw",
   "inputs": [
    {
     "name": "amount",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  }
 ],
 "TYBGacha": [
  {
   "type": "error",
   "name": "AlreadyDone",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadCommit",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadParams",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadQuantity",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadWinningIds",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BuysPausedErr",
   "inputs": []
  },
  {
   "type": "error",
   "name": "CommitReused",
   "inputs": []
  },
  {
   "type": "error",
   "name": "Insolvent",
   "inputs": []
  },
  {
   "type": "error",
   "name": "LiveSetDone",
   "inputs": []
  },
  {
   "type": "error",
   "name": "LiveSetNotFrozen",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotBuyer",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotConfirmed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NothingToDo",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotLower",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotOperator",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotWinningTicket",
   "inputs": []
  },
  {
   "type": "error",
   "name": "Overlap",
   "inputs": []
  },
  {
   "type": "error",
   "name": "OwnableInvalidOwner",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "OwnableUnauthorizedAccount",
   "inputs": [
    {
     "name": "account",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ReentrancyGuardReentrantCall",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RefundStillOpen",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SalesNotOver",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SalesOver",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SendFailed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "SweepNotReady",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TooEarly",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TooLate",
   "inputs": []
  },
  {
   "type": "error",
   "name": "WrongState",
   "inputs": []
  },
  {
   "type": "error",
   "name": "WrongValue",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ZeroAddress",
   "inputs": []
  },
  {
   "type": "event",
   "name": "BuysPausedSet",
   "inputs": [
    {
     "name": "paused",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "FastPathArmed",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "armedAt",
     "type": "uint64",
     "indexed": false,
     "internalType": "uint64"
    },
    {
     "name": "noWinner",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "FastPathCleared",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "by",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "nonce",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "FastPathClearedByOwner",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "LiveSetFrozen",
   "inputs": [
    {
     "name": "liveCount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "LiveSetProgress",
   "inputs": [
    {
     "name": "cursor",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "count",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OperatorSet",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OwnershipTransferred",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OwnershipTransferStarted",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "PayoutCredited",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "PotFunded",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "PotReclaimed",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "PurchaseSettled",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "refunded",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Pushed",
   "inputs": [
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RoundDustExpired",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RoundOpened",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "ticketPrice",
     "type": "uint128",
     "indexed": false,
     "internalType": "uint128"
    },
    {
     "name": "salesEnd",
     "type": "uint64",
     "indexed": false,
     "internalType": "uint64"
    },
    {
     "name": "seedCommit",
     "type": "bytes32",
     "indexed": false,
     "internalType": "bytes32"
    },
    {
     "name": "winningIds",
     "type": "uint16[]",
     "indexed": false,
     "internalType": "uint16[]"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RoundRefundEnabled",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "RoundResolved",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "seed",
     "type": "bytes32",
     "indexed": false,
     "internalType": "bytes32"
    },
    {
     "name": "resolveBlock",
     "type": "uint64",
     "indexed": false,
     "internalType": "uint64"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "SalesClosed",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "closeBlock",
     "type": "uint64",
     "indexed": false,
     "internalType": "uint64"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "StalePayoutExpired",
   "inputs": [
    {
     "name": "who",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "StalePrizeExpired",
   "inputs": [
    {
     "name": "who",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Swept",
   "inputs": [
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "TicketRefunded",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "buyer",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "TicketsBought",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "buyer",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "startNonce",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "localStartIndex",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "qty",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "WinnerFinalized",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "hasWinner",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    },
    {
     "name": "winningNonce",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "winner",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    },
    {
     "name": "prize",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "fastPath",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "WinningTicketSubmitted",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "nonce",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "buyer",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "nonceOffset",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "Withdrawn",
   "inputs": [
    {
     "name": "who",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "function",
   "name": "acceptOwnership",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "attestState",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "buildLiveSet",
   "inputs": [
    {
     "name": "maxIds",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "buysPaused",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "buyTickets",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "qty",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "claimable",
   "inputs": [
    {
     "name": "who",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "clearFastPath",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "closeSales",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "currentRoundId",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "distributeBatch",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndices",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "DUST_GRACE",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "expireRoundDust",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "expireStalePayout",
   "inputs": [
    {
     "name": "who",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "expireStalePrize",
   "inputs": [
    {
     "name": "who",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "finalizeWinner",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "forceRefund",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "fundPot",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "payable"
  },
  {
   "type": "function",
   "name": "lastActivityAt",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "lastCreditAt",
   "inputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "liveCount",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "liveCursor",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "liveIds",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint16",
     "internalType": "uint16"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "liveSetFrozen",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "MAX_SALES_WINDOW",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "MAX_TICKETS_PER_TX",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "MAX_WINNERS",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "MIN_SETTLE_BLOCKS",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "NO_WINNER_FAST_WINDOW",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "NO_WINNER",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "openRound",
   "inputs": [
    {
     "name": "ticketPrice",
     "type": "uint128",
     "internalType": "uint128"
    },
    {
     "name": "winningIds_",
     "type": "uint16[]",
     "internalType": "uint16[]"
    },
    {
     "name": "salesEnd",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "seedCommit",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "OPERATOR_FAST_WINDOW",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "operator",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "operatorAssertedAt",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint64",
     "internalType": "uint64"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "owner",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "payoutReserved",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pendingOwner",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pendingPayout",
   "inputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pendingPrize",
   "inputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "potReserved",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "prizeReserved",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "purchaseCount",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "purchases",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "buyer",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "startNonce",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "localStartIndex",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "qty",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "settled",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pushPayouts",
   "inputs": [
    {
     "name": "recipients",
     "type": "address[]",
     "internalType": "address[]"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "reclaimPot",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "refundTicket",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "renounceOwnership",
   "inputs": [],
   "outputs": [],
   "stateMutability": "pure"
  },
  {
   "type": "function",
   "name": "REVEAL_WINDOW",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "revealAndResolve",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "seed",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "rounds",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "ticketPrice",
     "type": "uint128",
     "internalType": "uint128"
    },
    {
     "name": "state",
     "type": "uint8",
     "internalType": "enum TYBGacha.State"
    },
    {
     "name": "winnerFinalized",
     "type": "bool",
     "internalType": "bool"
    },
    {
     "name": "hasWinner",
     "type": "bool",
     "internalType": "bool"
    },
    {
     "name": "potPaid",
     "type": "bool",
     "internalType": "bool"
    },
    {
     "name": "dustExpired",
     "type": "bool",
     "internalType": "bool"
    },
    {
     "name": "seedCommit",
     "type": "bytes32",
     "internalType": "bytes32"
    },
    {
     "name": "seed",
     "type": "bytes32",
     "internalType": "bytes32"
    },
    {
     "name": "salesEnd",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "revealDeadline",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "closeBlock",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "resolveBlock",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "resolveTs",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "finalizedAt",
     "type": "uint64",
     "internalType": "uint64"
    },
    {
     "name": "ticketCount",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "ticketETH",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "settledETH",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "livePot",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "winningNonce",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "winningPurchaseIndex",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "winningNonceOffset",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "winningBuyer",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "setBuysPaused",
   "inputs": [
    {
     "name": "p",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setOperator",
   "inputs": [
    {
     "name": "operator_",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "settlePurchase",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "submitWinningTicket",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "nonceOffset",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "SWEEP_GRACE",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "sweep",
   "inputs": [
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "sweepCeiling",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "ticketId",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "nonceOffset",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "transferOwnership",
   "inputs": [
    {
     "name": "newOwner",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "tyb721",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "unsettledTickets",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "usedCommits",
   "inputs": [
    {
     "name": "",
     "type": "bytes32",
     "internalType": "bytes32"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "walletTickets",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "WINNER_CLAIM_WINDOW",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "winningIdsOf",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint16[]",
     "internalType": "uint16[]"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "withdraw",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  }
 ],
 "TYBPowerUp1155": [
  {
   "type": "error",
   "name": "AlreadyClaimed",
   "inputs": []
  },
  {
   "type": "error",
   "name": "AlreadySet",
   "inputs": []
  },
  {
   "type": "error",
   "name": "EmptyPurchase",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ERC1155InsufficientBalance",
   "inputs": [
    {
     "name": "sender",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "balance",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "needed",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC1155InvalidApprover",
   "inputs": [
    {
     "name": "approver",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC1155InvalidArrayLength",
   "inputs": [
    {
     "name": "idsLength",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "valuesLength",
     "type": "uint256",
     "internalType": "uint256"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC1155InvalidOperator",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC1155InvalidReceiver",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC1155InvalidSender",
   "inputs": [
    {
     "name": "sender",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC1155MissingApprovalForAll",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidDefaultRoyalty",
   "inputs": [
    {
     "name": "numerator",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "denominator",
     "type": "uint256",
     "internalType": "uint256"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidDefaultRoyaltyReceiver",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidTokenRoyalty",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "numerator",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "denominator",
     "type": "uint256",
     "internalType": "uint256"
    }
   ]
  },
  {
   "type": "error",
   "name": "ERC2981InvalidTokenRoyaltyReceiver",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "EvolutionNotSet",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotEvolution",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotInPlay",
   "inputs": []
  },
  {
   "type": "error",
   "name": "OwnableInvalidOwner",
   "inputs": [
    {
     "name": "owner",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "OwnableUnauthorizedAccount",
   "inputs": [
    {
     "name": "account",
     "type": "address",
     "internalType": "address"
    }
   ]
  },
  {
   "type": "error",
   "name": "ReentrancyGuardReentrantCall",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RoundNotFinalized",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RoyaltyTooHigh",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ZeroAddress",
   "inputs": []
  },
  {
   "type": "event",
   "name": "ApprovalForAll",
   "inputs": [
    {
     "name": "account",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "operator",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "approved",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "BaseURISet",
   "inputs": [
    {
     "name": "base",
     "type": "string",
     "indexed": false,
     "internalType": "string"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "DefaultRoyaltySet",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "feeBps",
     "type": "uint96",
     "indexed": false,
     "internalType": "uint96"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "EvolutionSet",
   "inputs": [
    {
     "name": "evolution",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OwnershipTransferred",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "OwnershipTransferStarted",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "PowerUpsClaimed",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "buyer",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "qty",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "TransferBatch",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "from",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "ids",
     "type": "uint256[]",
     "indexed": false,
     "internalType": "uint256[]"
    },
    {
     "name": "values",
     "type": "uint256[]",
     "indexed": false,
     "internalType": "uint256[]"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "TransferSingle",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "from",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "indexed": true,
     "internalType": "address"
    },
    {
     "name": "id",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    },
    {
     "name": "value",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "URI",
   "inputs": [
    {
     "name": "value",
     "type": "string",
     "indexed": false,
     "internalType": "string"
    },
    {
     "name": "id",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "function",
   "name": "acceptOwnership",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "balanceOf",
   "inputs": [
    {
     "name": "account",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "id",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "balanceOfBatch",
   "inputs": [
    {
     "name": "accounts",
     "type": "address[]",
     "internalType": "address[]"
    },
    {
     "name": "ids",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256[]",
     "internalType": "uint256[]"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "burnForEvolve",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "category",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "qty",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "claimed",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "claimPowerUps",
   "inputs": [
    {
     "name": "roundId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "purchaseIndex",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "evolution",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "exists",
   "inputs": [
    {
     "name": "id",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "gacha",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "isApprovedForAll",
   "inputs": [
    {
     "name": "account",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "operator",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "N",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "owner",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pendingOwner",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "renounceOwnership",
   "inputs": [],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "royaltyInfo",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "salePrice",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "amount",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "safeBatchTransferFrom",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "ids",
     "type": "uint256[]",
     "internalType": "uint256[]"
    },
    {
     "name": "values",
     "type": "uint256[]",
     "internalType": "uint256[]"
    },
    {
     "name": "data",
     "type": "bytes",
     "internalType": "bytes"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "safeTransferFrom",
   "inputs": [
    {
     "name": "from",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "to",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "id",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "value",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "data",
     "type": "bytes",
     "internalType": "bytes"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setApprovalForAll",
   "inputs": [
    {
     "name": "operator",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "approved",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setBaseURI",
   "inputs": [
    {
     "name": "base",
     "type": "string",
     "internalType": "string"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setDefaultRoyalty",
   "inputs": [
    {
     "name": "receiver",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "feeBps",
     "type": "uint96",
     "internalType": "uint96"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "setEvolution",
   "inputs": [
    {
     "name": "e",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "supportsInterface",
   "inputs": [
    {
     "name": "interfaceId",
     "type": "bytes4",
     "internalType": "bytes4"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "totalSupply",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "totalSupply",
   "inputs": [
    {
     "name": "id",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "transferOwnership",
   "inputs": [
    {
     "name": "newOwner",
     "type": "address",
     "internalType": "address"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "uri",
   "inputs": [
    {
     "name": "id",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "string",
     "internalType": "string"
    }
   ],
   "stateMutability": "view"
  }
 ],
 "TYBEvolution": [
  {
   "type": "error",
   "name": "AlreadyPending",
   "inputs": []
  },
  {
   "type": "error",
   "name": "AlreadySettled",
   "inputs": []
  },
  {
   "type": "error",
   "name": "BadCategory",
   "inputs": []
  },
  {
   "type": "error",
   "name": "MaxLevel",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NMismatch",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotOwner",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ReentrancyGuardReentrantCall",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RoundAlreadyResolved",
   "inputs": []
  },
  {
   "type": "error",
   "name": "RoundNotResolved",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TooEarlyToCancel",
   "inputs": []
  },
  {
   "type": "error",
   "name": "UnknownAttempt",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ZeroAddress",
   "inputs": []
  },
  {
   "type": "event",
   "name": "AttemptCancelled",
   "inputs": [
    {
     "name": "attemptId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "category",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "AttemptCommitted",
   "inputs": [
    {
     "name": "attemptId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "category",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "targetLvl",
     "type": "uint8",
     "indexed": false,
     "internalType": "uint8"
    },
    {
     "name": "committer",
     "type": "address",
     "indexed": false,
     "internalType": "address"
    },
    {
     "name": "pinnedRound",
     "type": "uint256",
     "indexed": false,
     "internalType": "uint256"
    }
   ],
   "anonymous": false
  },
  {
   "type": "event",
   "name": "AttemptResolved",
   "inputs": [
    {
     "name": "attemptId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "tokenId",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "category",
     "type": "uint256",
     "indexed": true,
     "internalType": "uint256"
    },
    {
     "name": "pass",
     "type": "bool",
     "indexed": false,
     "internalType": "bool"
    },
    {
     "name": "newLevel",
     "type": "uint8",
     "indexed": false,
     "internalType": "uint8"
    }
   ],
   "anonymous": false
  },
  {
   "type": "function",
   "name": "attempts",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "category",
     "type": "uint8",
     "internalType": "uint8"
    },
    {
     "name": "targetLvl",
     "type": "uint8",
     "internalType": "uint8"
    },
    {
     "name": "settled",
     "type": "bool",
     "internalType": "bool"
    },
    {
     "name": "committer",
     "type": "address",
     "internalType": "address"
    },
    {
     "name": "pinnedRound",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "commitTs",
     "type": "uint64",
     "internalType": "uint64"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "CANCEL_DEADLINE",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "cancelAttempt",
   "inputs": [
    {
     "name": "attemptId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "commitAttempt",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "category",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "attemptId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "gacha",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "contract ITYBGachaEvo"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "getLevel",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "category",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "uint8",
     "internalType": "uint8"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "levelsOf",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "out",
     "type": "uint8[]",
     "internalType": "uint8[]"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "N",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "nextAttemptId",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "pending",
   "inputs": [
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    },
    {
     "name": "",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "bool",
     "internalType": "bool"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "powerUp",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "contract ITYBPowerUpEvo"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "resolveAttempt",
   "inputs": [
    {
     "name": "attemptId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "tyb721",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "contract ITYB721Evo"
    }
   ],
   "stateMutability": "view"
  }
 ],
 "TYBRenderer": [
  {
   "type": "error",
   "name": "EmptyBase",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotOwnable",
   "inputs": []
  },
  {
   "type": "error",
   "name": "NotOwner",
   "inputs": []
  },
  {
   "type": "error",
   "name": "TrailingSlash",
   "inputs": []
  },
  {
   "type": "error",
   "name": "ZeroAddress",
   "inputs": []
  },
  {
   "type": "event",
   "name": "GwBaseSet",
   "inputs": [
    {
     "name": "gwBase",
     "type": "string",
     "indexed": false,
     "internalType": "string"
    }
   ],
   "anonymous": false
  },
  {
   "type": "function",
   "name": "gwBase",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "string",
     "internalType": "string"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "setGwBase",
   "inputs": [
    {
     "name": "gwBase_",
     "type": "string",
     "internalType": "string"
    }
   ],
   "outputs": [],
   "stateMutability": "nonpayable"
  },
  {
   "type": "function",
   "name": "tokenURI",
   "inputs": [
    {
     "name": "tokenId",
     "type": "uint256",
     "internalType": "uint256"
    }
   ],
   "outputs": [
    {
     "name": "",
     "type": "string",
     "internalType": "string"
    }
   ],
   "stateMutability": "view"
  },
  {
   "type": "function",
   "name": "tyb721",
   "inputs": [],
   "outputs": [
    {
     "name": "",
     "type": "address",
     "internalType": "address"
    }
   ],
   "stateMutability": "view"
  }
 ]
});
  if (typeof window !== 'undefined') window.TYB_ABI = TYB_ABI;
  if (typeof module !== 'undefined' && module.exports) module.exports = TYB_ABI;
})();
